import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../app/components/Banner";
import Membership from "../app/components/Membership";
import NewsLetter from "../app/components/NewsLetter";
import Services from "../app/components/Services";
import Statistics from "../app/components/Statistics";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Banner />
        <Statistics />
        <Services />
        <Membership />
        <NewsLetter />
      </main>
    </div>
  );
};

export default Home;
