import type { NextPage } from "next";
import Head from "next/head";
import About from "../app/components/About";
import HomePage from "../routes/Home";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Peaqock Financials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
