import Head from "next/head";
import DashboardPage from "../../routes/Dashborad";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardPage />
    </>
  );
};

export default Dashboard;
