import Head from "next/head";
import SearchPage from "../../routes/Dashborad/Search";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard | Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchPage />
    </>
  );
};

export default Dashboard;
